[project]
name = "mal-manga"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "ipykernel>=7.1.0",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
]
